import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Assignment</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav className={styles.mainnav}>
        <ul>
          <li>Products</li>
          <li>Company</li>
          <li>Case Study</li>
          <li>Support</li>
          <li>Contact</li>
        </ul>
      </nav>
      <div className={styles.Cmplogo}>
        <img src='/logo.png'></img>
      </div>
      <li className={styles.button}><span>Try For Free</span></li>
      <div className={styles.headline}>
          <li>World’s First Aluminum</li>
          <li>Alloy Machined Gold</li>
          <li>Purity Detector.</li>
      </div>
      <div className={styles.spex}>
          <li>Detect 25+ Elements precisely better than Fire Assay</li>
      </div>
      <li className={styles.button2}><span>Contact Sales</span></li>
      <li className={styles.button3}><span>Know more</span></li>
      <div className={styles.product}>
        <img src='/product.png'></img>
      </div>
      <div className={styles.container2}>
        <div className={styles.headline2}>
            <li>Experience the ultimate in convenience and</li>
            <li>quality with our innovative product</li>
        </div>
        <div className={styles.container3}>
          <li>Laser Machines</li>
          <div className={styles.headline3}>
            <p>It is a long established fact that a reader</p>
            <span> will be distracted</span>
            <img src='/product2.png'></img>
            <p className={styles.button5}>Learn More 🡢</p>
          </div>
        </div>
        <div className={styles.container4}>
          <li>Gold Purity Analyser</li>
          <div className={styles.headline3}>
            <p>It is a long established fact that a reader</p>
            <span> will be distracted</span>
            <img src='/product3.png'></img>
            <p className={styles.button5}>Learn More 🡢</p>
          </div>
        </div>
      </div>
      <img src='/image2.png' className={styles.image2}></img>
      <div className={styles.container5}>
      <img src='/image1.png'></img>
        <li>Solution sets for every business</li>
        <li>type and size</li>
        <p>Jewelry and banking 🡢</p>
        <div className={styles.para1}>
          <li>It is a long established fact that a reader will be distracted </li>
          <li>by the readable content of a page when looking at its</li>
          <li>layout.</li>
          <p>Hallmarking & Testing Labs</p>
        </div>
        <div className={styles.para1}>
          <li>It is a long established fact that a reader will be</li> 
          <li>distracted by the readable content.</li>
          <p>Laser Marking, Soldering & Cutting</p>
          <li>It is a long established fact that a reader will be distracted by the </li>
          <li>readable content of a page when looking at its layout.</li>
        </div>
      </div>
    </div>
  )
}
